const OPTIONS_ALLOWED = {
  DOCUMENT_TEXT_DETECTION: 'DOCUMENT_TEXT_DETECTION',
  FACE_DETECTION: 'FACE_DETECTION',
  LABEL_DETECTION: 'LABEL_DETECTION',
  LANDMARK_DETECTION: 'LANDMARK_DETECTION',
  OBJECT_LOCALIZATION: 'OBJECT_LOCALIZATION',
  SAFE_SEARCH_DETECTION: 'SAFE_SEARCH_DETECTION',
  TEXT_DETECTION: 'TEXT_DETECTION',
  WEB_DETECTION: 'WEB_DETECTION',
};

export default OPTIONS_ALLOWED;
